In [1]:
import pandas as pd
import talib

In [2]:
data_full = pd.read_csv('Dataset/test.csv')
indicators = talib.get_functions()

In [3]:
data_full

,ts,o,h,l,c,vol,volCcy,volCcyQuote,confirm
0,1640969940000,47485.5,47519.9,47443.3,47476.1,12.148750,5.768326e+05,5.768326e+05,1
1,1640969880000,47536.2,47538.7,47432.0,47485.5,26.707046,1.267923e+06,1.267923e+06,1
2,1640969820000,47566.8,47566.8,47517.6,47536.2,10.776975,5.122202e+05,5.122202e+05,1
3,1640969760000,47493.3,47570.0,47466.8,47566.7,24.330524,1.156349e+06,1.156349e+06,1
4,1640969700000,47599.4,47599.6,47454.0,47493.4,24.941196,1.184888e+06,1.184888e+06,1
...,...,...,...,...,...,...,...,...,...
2874,1640797500000,47699.5,47700.9,47699.4,47700.9,0.087606,4.178743e+03,4.178743e+03,1
2875,1640797440000,47674.5,47706.0,47666.9,47699.5,2.181096,1.039906e+05,1.039906e+05,1
2876,1640797380000,47690.1,47690.1,47670.0,47673.2,1.902989,9.073440e+04,9.073440e+04,1
2877,1640797320000,47726.9,47726.9,47692.2,47692.2,1.061390,5.063810e+04,5.063810e+04,1
2878,1640797260000,47675.0,47735.3,47674.9,47726.8,1.963055,9.363799e+04,9.363799e+04,1

In [4]:
indicators = talib.get_functions()
data_full['SMA'] = talib.MA(data_full['c'], timeperiod = 20)

In [5]:
import ta
df = ta.add_all_ta_features(data_full, "o", "h", "l", "c", "vol", fillna=True)

In [6]:
df.dropna(inplace=True)

In [7]:
df

,ts,o,h,l,c,vol,volCcy,volCcyQuote,confirm,SMA,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
19,1640968800000,47899.1,47918.6,47894.3,47918.5,1.783747,85441.549639,85441.549639,1,47726.030,...,0.231890,0.201776,0.030114,-31.438021,-9.201939,-22.236082,47849.574097,0.029851,0.029847,0.931837
20,1640968740000,47900.0,47900.0,47881.5,47899.2,1.737565,83217.128475,83217.128475,1,47747.185,...,0.225338,0.206488,0.018850,-35.964376,-14.554426,-21.409950,47851.314232,-0.040277,-0.040285,0.891185
21,1640968680000,47897.2,47899.5,47880.0,47897.2,3.636616,174161.535803,174161.535803,1,47767.770,...,0.217299,0.208650,0.008649,-38.339397,-19.311420,-19.027977,47851.819256,-0.004175,-0.004176,0.886973
22,1640968620000,47914.5,47918.0,47900.0,47900.0,1.069737,51250.549642,51250.549642,1,47785.960,...,0.208986,0.208718,0.000269,-42.645755,-23.978287,-18.667468,47852.418169,0.005846,0.005846,0.892870
23,1640968560000,47927.1,47927.2,47900.0,47911.6,5.009514,239984.047888,239984.047888,1,47803.205,...,0.202022,0.207378,-0.005356,-42.536905,-27.690011,-14.846894,47855.525432,0.024217,0.024214,0.917304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2874,1640797500000,47699.5,47700.9,47699.4,47700.9,0.087606,4178.743109,4178.743109,1,47679.060,...,0.024714,0.028222,-0.003508,-42.455912,-35.289159,-7.166752,47659.088599,0.109972,0.109912,0.473501
2875,1640797440000,47674.5,47706.0,47666.9,47699.5,2.181096,103990.625728,103990.625728,1,47679.975,...,0.025477,0.027673,-0.002196,-40.832701,-36.397868,-4.434834,47660.508467,-0.002935,-0.002935,0.470553
2876,1640797380000,47690.1,47690.1,47670.0,47673.2,1.902989,90734.400513,90734.400513,1,47680.925,...,0.021385,0.026415,-0.005031,-40.024519,-37.123198,-2.901321,47660.625128,-0.055137,-0.055152,0.415156
2877,1640797320000,47726.9,47726.9,47692.2,47692.2,1.061390,50638.095204,50638.095204,1,47681.790,...,0.021113,0.025355,-0.004242,-41.731473,-38.044853,-3.686620,47660.770587,0.039855,0.039847,0.455176
2878,1640797260000,47675.0,47735.3,47674.9,47726.8,1.963055,93637.987706,93637.987706,1,47686.845,...,0.026448,0.025574,0.000874,-40.071416,-38.450165,-1.621250,47661.944443,0.072549,0.072522,0.528055

In [8]:
df.to_csv('Dataset/test1.csv', index=False)

In [9]:
# h = h
# l = low
# o = o
# c = c
# v = vol

indicators = ta.get_functions()

indicators.remove('AD')
indicators.remove('ADOSC')
indicators.remove('MFI')
indicators.remove('OBV')

hlcv_indicators = ['AD','ADOSC','MFI']
cl_indicators = ['OBV']


data_full_with_indi = []




# data_full = data_full.copy()
for indicator in indicators:
    print(indicator)        # indi need 1 value
    try: 
        name = ta.Function(indicator)(data_full['c'])
        if len(name)>100:
            data_full[indicator] = name
        else:
            for i in range(len(name)):
                data_full[indicator] = name[i]
    except Exception as e:
        print(e)
        # print(e)

    # indi need 2 value
    try: 
        name = ta.Function(indicator)(data_full['h'],data_full['l'])
        if len(name)>100:
            data_full[indicator] = name
        else:
            for i in range(len(name)):
                data_full[indicator] = name[i]
    except Exception as e:
        print(e) 

    # indi need 3 value       
    try:
        name = ta.Function(indicator)(data_full['h'],data_full['l'],data_full['c'])
        if len(name)>100:
            data_full[indicator] = name
        else:
            for i in range(len(name)):
                data_full[indicator] = name[i]
    except Exception as e:
        print(e)

    # indi need 4 value
    try: 
        name = ta.Function(indicator)(data_full['o'],data_full['h'],data_full['l'],data_full['c'])
        if len(name)>100:
            data_full[indicator] = name
        else:
            for i in range(len(name)):
                data_full[indicator] = name[i]
    except Exception as e:
        print(e)

# others indi that need specific value
for hlcv_indicator in hlcv_indicators:
    try: 
        name = ta.Function(hlcv_indicator)(data_full['o'],data_full['h'],data_full['c'],data_full['vol'])
        if len(name)>100:
            data_full[indicator] = name
        else:
            for i in range(len(name)):
                data_full[indicator] = name[i]
    except Exception as e:
        print(e) 
for cl_indicator in cl_indicators:
    try: 
        name = ta.Function(cl_indicator)(data_full['c'],data_full['vol'])
        if len(name)>100:
            data_full[indicator] = name
        else:
            for i in range(len(name)):
                data_full[indicator] = name[i]
    except Exception as e:
        print(e) 
data_full_with_indi.append(data_full)


data_full_full = []

AttributeError: module 'ta' has no attribute 'get_functions'

In [ ]:
data_with_indi

['ts', 'o', 'h', 'l', 'c', 'vol', 'volCcy', 'volCcyQuote', 'confirm']